# Generated by Django 3.0.8 on 2020-07-29 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200729_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
        migrations.AddField(
            model_name='search',
            name='SearchDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 29, 10, 21, 59, 562807), verbose_name='Search Date'),
            preserve_default=False,
        ),
    ]
